### PR TITLE
Refine user operation

### PR DESCRIPTION
**Pull request by pilagod**
Extract `UserOperation` class ([link](https://github.com/pilagod/waallet-extension/blob/0ee623c5f1ce45e0cb02903f02ea54efba0c4efd/packages/provider/bundler/index.ts#L9)), and put related functions on it.

### CODE REVIEW

**Comment by oneleo** [comment]
Encountering an error in tabs/userOperationAuthorization.tsx while swapping on the Uniswap DApp.
This leads to a blank page in userOperationAuthorization (not observed in the local Waallet-Dapp).
Investigating the cause currently.

<details>
  <summary>( Please click here to expand )</summary>
    <pre><code>

Uncaught TypeError: invalid value for Contract target (argument="target", value=null, code=INVALID_ARGUMENT, version=6.11.1)
    at makeError (errors.ts:688:13)
    at assert (errors.ts:716:1)
    at assertArgument (errors.ts:727:48)
    at new BaseContract (contract.ts:689:40)
    at new Contract (contract.ts:1120:50)
    at new VerifyingPaymaster (index.ts:22:10)
    at UserOperationAuthorization (userOperationAuthorization.tsx:40:16)
    at renderWithHooks (react-dom.development.js:16307:7)
    at mountIndeterminateComponent (react-dom.development.js:20075:13)
    at beginWork (react-dom.development.js:21590:10)
react-dom.development.js:18694 The above error occurred in the <UserOperationAuthorization> component:
_
    at UserOperationAuthorization (chrome-extension://imaadogakjipofgdnmcbeijdmcgedcbp/tabs/userOperationAuthorization.63db3e23.js:25177:24)
_
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18694
Show 1 more frame
Show less
react-dom.development.js:26924 Uncaught TypeError: invalid value for Contract target (argument="target", value=null, code=INVALID_ARGUMENT, version=6.11.1)
    at makeError (errors.ts:688:13)
    at assert (errors.ts:716:1)
    at assertArgument (errors.ts:727:48)
    at new BaseContract (contract.ts:689:40)
    at new Contract (contract.ts:1120:50)
    at new VerifyingPaymaster (index.ts:22:10)
    at UserOperationAuthorization (userOperationAuthorization.tsx:40:16)
    at renderWithHooks (react-dom.development.js:16307:7)
    at mountIndeterminateComponent (react-dom.development.js:20075:13)
    at beginWork (react-dom.development.js:21590:10)
    </code></pre>
</details>

**Comment by oneleo** [comment]
Review note:
1. It introduces a `UserOperation` class for seamless handling and offers a `data()` method, mainly converting `BigInt` to `Hex`.
2. Using classes helps centralize data processing. If conversion methods change in the future, modifying the class suffices for global adjustments.

**Review by oneleo — APPROVED** [review]

**Review by ChiHaoLu — APPROVED** [review]

**Comment by ChiHaoLu** [comment]
I need to spend more time to familiar with extension part haha... But LGTM!

**Comment by oneleo** [comment]
> @oneleo I think it's because we don't have a valid verifying paymaster on testnet. Maybe we can think up a way to automatically ignore invalid paymaster.

Yes, indeed! I submitted a [PR to waallet-contract](https://github.com/pilagod/waallet-contract/pull/24) and [deployed a test Paymaster](https://sepolia.etherscan.io/address/0x794ae45b5bfe6f40940eac328b2ddfbb3be312c0#readContract).
Or, we can discuss creating a new PR to check for the Paymaster's existence.

**Comment by pilagod** [comment]
@ChiHaoLu Learn from PR is one way to quickly get involved 💪 

One thing you must pay attention to is that the account interface is slightly changed in this PR, this might affect your design for new account.

**Pull request merged**
